[build]
  publish = "."
  command = "cd frontend && yarn install && yarn build && cp -r build/* .."

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/api/*"
  to = "https://project-merger.preview.emergentagent.com/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200